name: huddle
services:
  devcontainer:
    container_name: devcontainer
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        GO_VERSION: ${GO_VERSION}
        AWS_CLI_VERSION: ${AWS_CLI_VERSION}
        AWS_CDK_VERSION: ${AWS_CDK_VERSION}
        NODE_VERSION: ${NODE_VERSION}
    volumes:
      - ./:/workspace:rw
    environment:
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
    command: sleep infinity

